[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
rust-version = "1.85"
edition = "2021"

[workspace.dependencies]
# local crates
did = { path = "./crates/did", version = "0.0.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

# non-local crates
