[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
rust-version = "1.85"
edition = "2021"

[workspace.dependencies]
# local crates
crypto = { path = "./crates/openmls-group", version = "0.0.0" }

# non-local crates
